apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: salesacr.azurecr.io/sales-reports-app:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_HOST
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_NAME
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fastapi-secret
                key: DATABASE_PASSWORD