name: Build & Deploy FastAPI

on:
  push:
    branches:
      - main

env:
  ACR_NAME: salesacr
  ACR_LOGIN_SERVER: salesacr.azurecr.io
  IMAGE_NAME: sales-reports-app
  AKS_RESOURCE_GROUP: sales-rg
  AKS_CLUSTER_NAME: sales-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up AKS context
      run: |
        az aks get-credentials \
          --resource-group $AKS_RESOURCE_GROUP \
          --name $AKS_CLUSTER_NAME \
          --overwrite-existing

    - name: Log in to ACR
      run: |
        az acr login --name $ACR_NAME

    - name: Build and push Docker image
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

    - name: Update Kubernetes manifests
      run: |
        # Aktualizacja obrazu w pliku deployment
        sed -i "s|image: .*$|image: $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}|" k8s/fastapi-deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/
        kubectl rollout restart deployment fastapi-deployment
    